Reserveringssysteem(background+WPF)
Tygozwolle/boten pull request #41
Opened 2024-04-26 15:38 UTC by sting-byte

alle logica voor het maken van een eservering zit erin en werkt. De wpf is ook 100% functioneel

2024-04-26 15:44 UTC, Tygozwolle requested changes

2024-04-26 15:44 UTC, Tygozwolle commented on RoeiVerenigingWPF/App.xaml
> +             StartupUri="/Pages/AddReservation.xaml">
je bent vergeten dit terug te zetten

2024-04-26 16:13 UTC, Tygozwolle submitted a review, later dismissed
als ik een boot in het verleden reserveer krijg ik geen melding. er zijn nog geen unit testen gemaakt.
zou je ook nog een bevestiging willen toevoegen?

2024-04-26 16:13 UTC, Tygozwolle commented on RoeiVerenigingWPF/Pages/AddReservation.xaml.cs
> +                return CurrentDateTime;
dit zorgt voor stackoverflow

2024-04-26 16:13 UTC, Tygozwolle commented on RoeiVerenigingLibary/ReservationCreator.cs
> +    private int UserId { get; set; }
waaom user id deze zit all in member?

2024-04-26 16:13 UTC, Tygozwolle commented on RoeiVerenigingLibary/ReservationCreator.cs
> +    public string? Email { get; set; }
waarom email ? is niet nodig voor reservering zit al bij member in

2024-04-26 16:13 UTC, Tygozwolle commented on RoeiVerenigingWPF/Pages/AddReservation.xaml.cs
> +        private Member _member = new Member(30,  "rick", "wil", "roeien", "rick@windesheim.be", new List<string>());
nu komt de reservering altijd op rick zijn naam te staan terwijl dit de ingelogde gebruiker moet zijn

2024-04-26 16:24 UTC, Tygozwolle commented on RoeiVerenigingWPF/Pages/AddReservation.xaml.cs
> +        private Member _member = new Member(30,  "rick", "wil", "roeien", "rick@windesheim.be", new List<string>());
Staat al in master. Is in account aanmaken al toegepast

2024-04-26 16:31 UTC, Tygozwolle commented on RoeiVerenigingWPF/Pages/AddReservation.xaml.cs
> +            get
Deze moet gefixt worden.
Voordat je ze sluit moet je eerst kijken wat ze inhouden

2024-05-06 18:48 UTC, YeetusDeletus2 approved these changes

2024-05-07 08:03 UTC, willekeh requested changes

2024-05-07 08:04 UTC, YeetusDeletus2 commented on DataAccessLibary/MemberRepository.cs
> +        return null;
anders crashed die

2024-05-07 08:10 UTC, merged