Botenlijst
Tygozwolle/boten pull request #51
Opened 2024-05-13 07:43 UTC by willekeh

2024-05-13 08:02 UTC, Simon6837 requested changes

2024-05-13 08:02 UTC, Simon6837 commented on RoeiVerenigingWPF/Pages/ListBoats.xaml
> +                                                <TextBlock Text="{Binding CaptainSeat, StringFormat='Stuurman? {0}'}" VerticalAlignment="Center" HorizontalAlignment="Right"/>
Hier staat true of false. kan dit niet beter iets zijn van "stuurman positie aanwezig" en dit alleen laten zien als dit er is?

2024-05-13 08:03 UTC, Simon6837 requested changes
Branch is nog de nieuwe code van master nodig om te kunnen mergen

2024-05-13 08:12 UTC, Simon6837 requested changes
De unit tests missen

2024-05-13 11:04 UTC, Tygozwolle requested changes
je test faalt

2024-05-13 11:18 UTC, Tygozwolle requested changes

2024-05-13 11:18 UTC, Tygozwolle commented on RoeiVerenigingLibary/Boat.cs
> +        //public Url Image { get; set; }
deze regel zit niet in database moet verwijderd worden. komt apparte tabel voor met afbeeldingen

2024-05-13 11:44 UTC, Tygozwolle requested changes
boot heeft nog geen niveau

2024-05-14 08:43 UTC, Simon6837 approved these changes

2024-05-14 08:50 UTC, Tygozwolle approved these changes

2024-05-14 08:50 UTC, merged